version: '3'

services:

  s3-services:
    build:
      context: ./S3ServiceOperator
    ports:
      - "8000:8000"
    networks:
      - knowledgeflow-network

  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - knowledgeflow-network

  knowledge-tree-manager:
    build:
      context: ./KnowledgeTreeManager
    ports:
      - "5000:5000"
    environment:
      - S3_SERVICE_URL=http://s3-services:8000
    networks:
      - knowledgeflow-network

networks:

  knowledgeflow-network:
    driver: bridge
